<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="QSP" failures="1" tests="2" name="Default test" time="1.145" errors="0" timestamp="2024-02-02T11:51:54 IST">
  <testcase classname="Listenners.Skipped" name="m1" time="1.042">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method Listenners.Skipped.m1() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Listenners.Skipped.m1() didn't finish within the time-out 1000
at java.base@17.0.9/java.lang.Thread.sleep(Native Method)
at app//Listenners.Skipped.m1(Skipped.java:9)
at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.9/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.9/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.9/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.9/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.9/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- m1 -->
  <testcase classname="Listenners.Skipped" name="m2" time="0.001">
    <skipped/>
  </testcase> <!-- m2 -->
</testsuite> <!-- Default test -->
